package lv.itsms.web.command;

public enum CommandTypeParameter {
	NO_COMMAND, 
	CMD_DELETE_SMS_GROUP_REC,
	CMD_LOAD_SMS_GROUP_NAMES, 
	CMD_LOAD_SMS_GROUP_REC,
	CMD_OPEN_NEW_SMS_REC, 
	CMD_SAVE_SMS_GROUP_REC,
	CMD_VIEW_REPORT_DIAGRAM,
	CMD_DO_LOGIN_USER;
}
